import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ConfigProvider, Layout } from "antd";
import AppHeader from "./components/AppHeader";
import { Footer } from "antd/es/layout/layout";
import AppFooter from "./components/AppFooter";

const font = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#012030",
              fontFamily: "Montserrat",
            },
          }}
        >
          <AppHeader />
          <div>{children}</div>
          <Footer className="bg-background">
            <AppFooter />
          </Footer>
        </ConfigProvider>
      </body>
    </html>
  );
}
